name: Deploy static site

on:
  push:
    tags: ['v*']   # v1.0.0, v1.2.3

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read version from tag
        id: ver
        run: echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      # Create an artifact with the root 'public/' folder.
      - name: Build artifact (wrap to public/)
        run: |
          mkdir -p artifact/public
          cp -r ./* artifact/public/ || true
          # remove .git and the artifact folder itself from artifacts.
          rm -rf artifact/public/.git artifact/public/artifact
          # Make sure that index.html exists
          test -f artifact/public/index.html
          # Pack everything
          cd artifact
          tar -czf ../yuriisoft.tar.gz .

      - name: Copy files to Server
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          # Копируем два файла: архив и скрипт деплоя
          source: "yuriisoft.tar.gz, .scripts/deploy.sh"
          target: "/tmp/"

      - name: Deploy on Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Give permissions to execute the file (just in case)
            chmod +x /tmp/.scripts/deploy.sh
            
            # Run the script, passing it parameters
            # 1 argument is a tag name
            # 2 argument is a path to the archive
            # 3 argument is a path to the directory to deploy to
            ${{ steps.ver.outputs.VERSION }} /tmp/.scripts/deploy.sh /tmp/yuriisoft.tar.gz /srv/apps/yuriisoft
            
            # Cleaning up unused files after deploy
            rm /tmp/release.tar.gz
            rm -rf /tmp/.scripts